const quoteSpanishProfesional1 = [{id: 0, quote:"El único modo de hacer un gran trabajo es amar lo que haces", author: "Steve Jobs"},
    {id: 1,quote:"Nunca pienso en las consecuencias de fallar un gran tiro… cuando se piensa en las consecuencias se está pensando en un resultado negativo ", author: "Michael Jordan"},
    {id: 2,quote:"El dinero no es la clave del éxito; la libertad para poder crear lo es ", author: "Nelson Mandela"},
    {id: 3,quote:"Cuanto más duramente trabajo, más suerte tengo", author: "Gary Player"},
    {id: 4,quote:"La inteligencia consiste no sólo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica", author: "Aristóteles"},
    {id: 5,quote:"El trabajo duro hace que desaparezcan las arrugas de la mente y el espíritu", author: "Helena Rubinstein"},
    {id: 6,quote:"Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades de que salga bien no te acompañan ", author: "Elon Musk"},
    {id: 7,quote:"Escoge un trabajo que te guste, y nunca tendrás que trabajar ni un solo día de tu vida", author: "Confucio"},
    {id: 8,quote:"Un sueño no se hace realidad por arte de magia, necesita sudor, determinación y trabajo duro ", author: "Colin Powell"},
    {id: 9,quote:"Cuéntamelo y me olvidaré. enséñamelo y lo recordaré. involúcrame y lo aprenderé ", author: "Benjamin Franklin "},
    {id: 10,quote:"La lógica te llevará de la a a la z. la imaginación te llevará a cualquier lugar", author: "Albert Einstein"},
    {id: 11,quote:"A veces la adversidad es lo que necesitas encarar para ser exitoso", author: "Zig Ziglar "},
    {id: 12,quote:"Para tener éxito tu deseo de alcanzarlo debe ser mayor que tu miedo al fracaso ", author: "Bill Cosby"},
    {id: 13,quote:"Ejecuta tus conocimientos con la maestría del que sigue aprendiendo", author: "Jonathan García-Allen"}
];

const quoteSpanishShorts2 = [
    {id:0 ,quote: "Cuando pierdas, no pierdas la lección", author: "Dalai Lama "},
    {id:1 ,quote: "No busques los errores, busca un remedio", author: "Henry Ford"},
    {id:2 ,quote: "La vida es una aventura, atrévete ", author: "Teresa de Calcuta"},
    {id:3 ,quote: "Tu actitud, no tu aptitud, determinará tu altitud ", author: "Zig Ziglar"},
    {id:4 ,quote: "Tienes que hacer las cosas que crees que no puedes hacer ", author: "Eleanor Roosevelt"},
    {id:5 ,quote: "Si te caíste ayer, levántate hoy ", author: "H. G. Wells"},
    {id:6 ,quote: "Siempre parece imposible... hasta que se hace ", author: "Nelson Mandela"},
    {id:7 ,quote: "Si no pierdes, no puedes disfrutar de las victorias ", author: "Rafael Nadal"},
    {id:8 ,quote: "No dejes que el miedo se interponga en tu camino", author: "Babe Ruth"},
    {id:9 ,quote: "Haz de cada día tu obra maestra", author: "John Wooden "},
    {id:10 ,quote: "No cuentes los días, haz que los días cuenten", author: "Muhammad Ali"},
    {id:11 ,quote: "El mejor momento del día es ahora ", author: "Pierre Bonnard"},
    {id:12 ,quote: "Si la oportunidad no llama, construye una puerta ", author: "Milton Berle"},
    {id:13 ,quote: "Deja que cada hombre ejerza el arte que domina ", author: "Aristófanes "},
    {id:14 ,quote: "El valor de una idea radica en su uso", author: "Thomas Edison"},
];

const quoteSpanishPersonalGrowth3 = [
    {id:0 ,quote: "Piensa, sueña, cree y atrévete", author: "Walt Disney"},
    {id:1 ,quote: "Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta ", author: "Henry Ford"},
    {id:2 ,quote: "Asegúrate de que colocas tus pies en el lugar correcto, y luego mantente firme", author: "Abraham Lincoln"},
    {id:3 ,quote: "Las ideas pueden cambiar la vida. A veces a lo único que tienes que abrir la puerta es a una buena idea ", author: "Jim Rohn"},
    {id:4 ,quote: "La mejor manera para empezar es callándote y empezar a hacer ", author: "Walt Disney"},
    {id:5 ,quote: "Nadie se desembaraza de un hábito o de un vicio tirándolo de una vez por la ventana; hay que sacarlo por la escalera, peldaño a peldaño", author: "Mark Twain"},
    {id:6 ,quote: "Si te caes siete veces, levántate ocho ", author: "Proverbio chino"},
    {id:7 ,quote: "La perfección no es alcanzable, pero si perseguimos la perfección podemos conseguir la excelencia ", author: "Vince Lombardi"},
    {id:8 ,quote: "Tienes que esperar cosas de ti mismo antes de poder hacerlas ", author: "Michael Jordan"},
    {id:9 ,quote: "Transforma tus heridas en sabiduría ", author: "Oprah Winfrey"},
    {id:10 ,quote: "La edad no es barrera. Es una limitación que pones en tu mente", author: "Jackie Joyner-Kersee"},
    {id:11 ,quote: "Solo aquellos que se arriesgan a ir demasiado lejos pueden descubrir lo lejos que pueden llegar", author: "T.S. Eliot"},
    {id:12 ,quote: "Del sufrimiento emergieron las almas más fuertes, los caracteres sólidos tienen cicatrices", author: "Khalil Gibran"},
    {id:13 ,quote: "El universo no conspira contra ti, pero tampoco se desvía para alinear tu camino", author: "Tim Ferriss"},
    {id:14 ,quote: "Con autodisciplina casi todo es posible", author: "Theodore Roosevelt"},
    {id:15 ,quote: "", author: ""},
    {id:16 ,quote: "", author: ""}
];

const quoteSpanishCelebrated4 = [
    {id:0 ,quote: "La innovación distingue al líder del seguidor ", author: "Steve Jobs "},
    {id:1 ,quote: "Si puedes soñarlo, puedes hacerlo", author: "Walt Disney"},
    {id:2 ,quote: "El secreto para salir adelante es comenzar ", author: "Mark Twain"},
    {id:3 ,quote: "Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta ", author: "Henry Ford"},
    {id:4 ,quote: "La vida es como montar en bicicleta. para mantener el equilibrio tienes que avanzar", author: "Albert Einstein"},
    {id:5 ,quote: "El éxito no es definitivo, el fracaso no es fatídico. Lo que cuenta es el valor para continuar ", author: "Winston Churchill"},
    {id:6 ,quote: "Sé valiente. Toma riesgos. Nada puede sustituir la experiencia", author: "Paulo Coelho"},
    {id:7 ,quote: "El futuro pertenece a aquellos que creen en la belleza de sus sueños", author: "Eleanor Roosevelt"},
    {id:8 ,quote: "El conocimiento es poder ", author: "Francis Bacon"},
    {id:9 ,quote: "He aprendido que el valor no es la ausencia de miedo, sino el triunfo sobre él. El hombre valiente no es el que no siente miedo, sino el que lo domina ", author: "Nelson Mandela"},
    {id:10 ,quote: "Solo puede ser feliz siempre el que sabe ser feliz con todo", author: "Confucio "},
    {id:11 ,quote: "Es la capacidad de resistir a los errores lo que a menudo conduce a un mayor éxito ", author: "J. K. Rwolling"},
    {id:12 ,quote: "Aferrarse al rencor es como beber veneno y esperar que otra persona muera ", author: " Buda"},
    {id:13 ,quote: "No pares cuando estés cansado. Para cuando hayas terminado", author: "Marilyn Monroe"},
    {id:14 ,quote: "El 80% del éxito se basa simplemente en insistir ", author: "Woody Allen"}
];

const quoteSpanishOfLife5 = [
    {id:0 ,quote: "Cree que puedes y casi lo habrás logrado", author: "Theodore Roosevelt"},
    {id:1 ,quote: "No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo", author: "Robin Williams"},
    {id:2 ,quote: "Si tienes un sueño y crees en él, corres el riesgo de que se convierta en realidad ", author: "Walt Disney"},
    {id:3 ,quote: "Nunca se es demasiado viejo para fijar otra meta o para soñar un nuevo sueño ", author: "C. S. Lewis"},
    {id:4 ,quote: "Lo que no te mata, te hace más fuerte ", author: "Friedrich Nietzsche"},
    {id:5 ,quote: "El hombre que mueve montañas comienza cargando pequeñas piedras ", author: "Confucio"},
    {id:6 ,quote: "Buenos amigos, buenos libros y una conciencia tranquila: esa es la vida ideal ", author: "Mark Twain"},
    {id:7 ,quote: "Un optimista ve una oportunidad en toda calamidad, un pesimista ve una calamidad en toda oportunidad ", author: "Winston Churchill"},
    {id:8 ,quote: "Solo aquellos que se arriesgan a caer pueden conseguir grandes cosas ", author: "Robert F. Kennedy"},
    {id:9 ,quote: "El éxito es la suma de pequeños esfuerzos, que se repiten día tras día ", author: "Robert Collier"},
    {id:10 ,quote: "Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo cuando intentas algo nuevo", author: "Brian Tracy"},
    {id:11 ,quote: "¿Por qué contentarnos con vivir a rastras cuando sentimos el anhelo de volar? ", author: "Hellen Keller"},
    {id:12 ,quote: "Entrega siempre más de lo que esperan de ti ", author: "Larry Page"},
    {id:13 ,quote: "Aprovecha las oportunidades que aparezcan, donde quiera que estén ", author: "Lakshmi Mittal "},
    {id:14 ,quote: "Nunca es demasiado tarde para ser lo que podrías haber sido", author: "George Eliot"}
];

const quoteSpanishPositive6 = [
    {id:0 ,quote: "Puedo aceptar el fracaso pero no puedo aceptar no intentarlo ", author: "Michael Jordan"},
    {id:1 ,quote: "La mejor forma de predecir el futuro es creándolo", author: "Abraham Lincoln "},
    {id:2 ,quote: "Un día despertarás y descubrirás que no tienes más tiempo para hacer lo que soñabas. El momento es ahora. Actúa ", author: "Paulo Coelho"},
    {id:3 ,quote: "Hoy eres un lector y mañana serás un líder ", author: "Margaret Fuller"},
    {id:4 ,quote: "Los dos guerreros más poderosos son la paciencia y el tiempo ", author: "León Tolstói"},
    {id:5 ,quote: "No puedes derrotar a la persona que nunca se rinde", author: "Babe Ruth"},
    {id:6 ,quote: "El secreto de tu éxito está determinado por tu agenda diaria ", author: "John C. Maxwell"},
    {id:7 ,quote: "Recordar que vas a morir, es la mejor manera que conozco para no pensar que tienes algo que perder. Ya estás desnudo. No hay ninguna razón para no seguir a tu corazón", author: "Steve Jobs"},
    {id:8 ,quote: "Se lo suficientemente valiente para vivir de forma creativa. El lugar creativo donde nadie ha estado ", author: "Alan Alda"},
    {id:9 ,quote: "Cuando dejo ir lo que soy, me convierto en lo que debería ser ", author: "Lao Tzu"},
    {id:10 ,quote: "Apunta a la luna. Si fallas, podrías dar a una estrella", author: "William Clement Stone "},
    {id:11 ,quote: "Existe al menos un rincón del universo que con toda seguridad puedes mejorar, y eres tú mismo ", author: "Aldous Huxley"},
    {id:12 ,quote: "El verdadero buscador crece y aprende, y descubre que siempre es el principal responsable de lo que sucede", author: "Jorge Bucay"},
    {id:13 ,quote: "Escribir es un oficio que se aprende escribiendo", author: "Simone de Beauvoir"},
    {id:14 ,quote: "La forma más rápida de cambiar es convivir con personas que ya son como quieres ser", author: "Reid Hoffman"}
];

const quoteSpanishBeHappy7 = [
    {id:0 ,quote: "La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente", author: "Jim Rohn"},
    {id:1 ,quote: "La alegría es contagiosa y siempre consigue descubrir una solución donde la lógica sólo encontró una explicación para el error", author: "Paulo Coelho"},
    {id:2 ,quote: "Vive la vida que amas. Ama la vida que vives ", author: "Bob Marley"},
    {id:3 ,quote: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito ", author: "Albert Schweitzer"},
    {id:4 ,quote: "Unas palabras amables, un libro cálido y una sonrisa honesta pueden hacer milagros ", author: "William Hazlitt"},
    {id:5 ,quote: "La verdadera felicidad consiste en hacer el bien ", author: "Aristóteles"},
    {id:6 ,quote: "El otoño se convierte en una nueva primavera cuando cada hoja es una flor ", author: "Albert Camus"},
    {id:7 ,quote: "El éxito es encontrar satisfacción en dar un poco más de lo que se recibe ", author: "Christopher Reeve"},
    {id:8 ,quote: "La alegría reside en la alegría del logro y en la emoción del esfuerzo creativo", author: "Franklin Roosevelt"},
    {id:9 ,quote: "La verdadera motivación procede de trabajar en cosas que nos importan", author: "Sheryl Sandberg"},
    {id:10 ,quote: "La felicidad no ocurre por casualidad, sino por elección", author: "Jim Rohn"},
    {id:11 ,quote: "No tienes poder sobre los acontecimientos exteriores , pero sí sobre tu mente. Aprende esto, y encontrarás tu fuerza ", author: "Marco Aurelio"},
    {id:12 ,quote: "La buena vida es una forma de pensar ", author: "Emilio Valcárcel"},
    {id:13 ,quote: "Puedes ser feliz allí donde estés ", author: "Joel Osteen"},
    {id:14 ,quote: "El término «felicidad» perdería todo su significado si no fuese compensado por la tristeza ", author: "Carl Jung"},
    {id:15 ,quote: "", author: ""},
    {id:16 ,quote: "", author: ""}
];

const quoteSpanishInspiring8 = [
    {id:1 ,quote: "Alguien se sienta en la sombra porque alguien plantó un árbol hace mucho tiempo", author: "Warren Buffett"},
    {id:2 ,quote: "Avanza con confianza en la dirección de tus sueños ", author: "Thoreau"},
    {id:3 ,quote: "La diligencia es la madre de la buena suerte ", author: "Benjamin Franklin"},
    {id:4 ,quote: "Sólo se vive una vez. Pero si lo haces bien, una vez basta ", author: "Mae West"},
    {id:5 ,quote: "Da el primer paso con fe. No tienes que ver todas las escaleras, sólo da el  primer paso ", author: "Martin Luther King"},
    {id:6 ,quote: "Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que te importa de verdad se llama pasión", author: "Simon Sinek"},
    {id:7 ,quote: "El éxito depende del esfuerzo", author: "Sófocles"},
    {id:8 ,quote: "Intenta y falla, pero nunca falles en intentarlo ", author: "Jared Leto"},
    {id:9 ,quote: "No quiero ganarme la vida, quiero vivir", author: "Oscar Wilde"},
    {id:10 ,quote: "La vida no es un problema a ser resuelto, sino una realidad a experimentar", author: "Søren Aabye Kierkegaard"},
    {id:11 ,quote: "Háblate a ti mismo como harías con alguien a quien amas", author: "Brene Brown"},
    {id:12 ,quote: "Por más difícil que parezca la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito ", author: "Stephen Hawking"},
    {id:13 ,quote: "El fracaso se convierte en éxito si aprendes de él ", author: "Malcolm Forbes"},
    {id:14 ,quote: "La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto", author: "Michael Altshuler"},
    {id:15 ,quote: "La única manera de encontrar los límites de lo posible es ir más allá de lo imposible", author: "Arthur C. Clarke"},
];

const quoteSpanishNice9 = [
    {id:1 ,quote: "Casi todas las cosas buenas que suceden en el mundo, nacen de una actitud de aprecio por los demás ", author: "Dalai Lama"},
    {id:2 ,quote: "Donde reina el amor, siempre sobran las leyes ", author: "Platón"},
    {id:3 ,quote: "Amarse a uno mismo es el comienzo de una larga vida romántica ", author: "Oscar Wilde"},
    {id:4 ,quote: "Nada de lo que vistes es más importante que tu sonrisa", author: "Connie Stevens"},
    {id:5 ,quote: "En cada forma de vida existe el deseo del amor ", author: "D. H. Lawrence"},
    {id:6 ,quote: "Todos nos necesitamos los unos a los otros ", author: "Leo Buscaglia"},
    {id:7 ,quote: "Antes moriría de pasión que de aburrimiento", author: "Vincent van Gogh"},
    {id:8 ,quote: "Solo hay una felicidad en la vida, amar y ser amado ", author: "George Sand"},
    {id:9 ,quote: "El amor propio es la fuente de todos los tipos de amor ", author: "Pierre Corneille"},
    {id:10 ,quote: "Cambias tu vida al cambiar tu corazón ", author: "Max Lucado"},
    {id:11 ,quote: "La sencillez es una forma de humildad y la sencillez es una señal de la verdadera grandeza ", author: "Vince Lombardi"},
    {id:12 ,quote: "El alma que hablar puede con los ojos, también puede besar con la mirada ", author: "Gustavo Adolfo Bécquer "},
    {id:13 ,quote: "El que ama, se hace humilde. Aquellos que aman, por decirlo de alguna manera, renuncian a una parte de su narcisismo ", author: "Sigmund Freud"},
    {id:14 ,quote: "Sólo porque alguien no te ame como tú quieres, no significa que no te ame con todo su ser", author: "Gabriel García Márquez"},
    {id:15 ,quote: "El amor no mira con los ojos, sino con el alma", author: "William Shakespeare"}
];

const quoteSpanishPositiveThinking10 = [
    {id:1 ,quote: "La mejor forma de olvidar las malas cosas de la vida es aprender a recordar las cosas buenas ", author: "Mark Amend"},
    {id:2 ,quote: "Árbol de la esperanza, mantente firme ", author: "Frida Kahlo"},
    {id:3 ,quote: "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo", author: "Winston Churchill"},
    {id:4 ,quote: "Tus acciones positivas combinadas con los pensamientos positivos generan éxitos ", author: "Shiv Khera"},
    {id:5 ,quote: "Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo", author: "Ana Frank"},
    {id:6 ,quote: "Un solo rayo de sol es suficiente para apartar muchas sombras ", author: "San Francisco de Asís"},
    {id:7 ,quote: "Cuando piensas en positivo, cosas buenas ocurren", author: "Matt Kemp"},
    {id:8 ,quote: "No podemos ayudar a todos, pero todo el mundo puede ayudar a alguien", author: "Ronald Reagan "},
    {id:9 ,quote: "Sé el cambio que quieres ver en el mundo", author: "Mahatma Gandhi "},
    {id:10 ,quote: "Cualquier cosa que la mente del hombre puede concebir y creer, puede ser conseguida", author: "Napoleon Hill"},
    {id:11 ,quote: "Si supiera que el mundo se acaba mañana, yo, hoy todavía, plantaría un árbol ", author: "Martin Luther King"},
    {id:12 ,quote: "Es impresionante. La vida cambia muy rápido, de un modo positivo, si la dejas", author: "Lindsey Vonn"},
    {id:13 ,quote: "La palabra «no» solo significa que empieces otra vez en un nivel superior ", author: "Peter Diamandis"},
    {id:14 ,quote: "La grandeza nace de pequeños comienzos ", author: "Sir Francis Drake"},
    {id:15 ,quote: "Pon tu corazón, mente y alma incluso en los actos más pequeños. Ese es el secreto del éxito ", author: "Swami Sivananda"},
];

const quoteEnglishLife1 = [
    {id:1 ,quote: "Not in doing what you like, but in liking what you do is the secret of happiness.", author: "J.M. Barrie"},
    {id:2 ,quote: "My father gave me the best advice of my life. He said, ``Whatever you do, don't wake up at 65 years old and think about what you should have done with your life.``", author: "George Clooney"},
    {id:3 ,quote: "My father used to say, ``Don't raise your voice. Improve your argument.``", author: "Archbishop Desmond Tutu"},
    {id:4 ,quote: "You are only young once. After that you have to think up some other excuse.", author: "Billy Arthur"},
    {id:5 ,quote: "Monsters are real, and ghosts are real too. They live inside us—and sometimes, they win.", author: "Stephen King"},
    {id:6 ,quote: "Life is what happens to us while we are making other plans.", author: "Allen Saunders"},
    {id:7 ,quote: "People who complain that they don't get all they deserve should congratulate themselves.", author: "The Irish Times "},
    {id:8 ,quote: "One good way to test your memory is to try to remember the things that worried you yesterday.", author: "Toronto Star"},
    {id:9 ,quote: "You're never too broken to be fixed.", author: "Jonathan Van Ness"},
    {id:10 ,quote: "Greed is envy with its sleeves rolled up.", author: "George F. Will "},
    {id:11 ,quote: "Never fear shadows. They simply mean there's a light shining nearby.", author: "Ruth E. Renkel"},
    {id:12 ,quote: "Let us endeavor so to live, that when we come to die, even the undertaker will be sorry.", author: "Mark Twain"},
    {id:13 ,quote: "You only have to do a very few things right in your life—so long as you don't do too many things wrong.", author: "Warren Buffett"},
    {id:14 ,quote: "Accept that some days you're the pigeon, and some days you're the statue.", author: "Roger C. Andersen"},
    {id:15 ,quote: "Success is falling nine times and getting up ten.", author: "Jon Bon Jovi "}
];

const quoteEnglishTime2 = [
    {id:1 ,quote: "Time is the longest distance between two places.", author: "Tennessee Williams"},
    {id:2 ,quote: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler"},
    {id:3 ,quote: "The best thing about the future is that it comes one day at a time.", author: "Abraham Lincoln"},
    {id:4 ,quote: "Don't spend time beating on a wall, hoping to transform it into a door.", author: "Coco Chanel"},
    {id:5 ,quote: "We must use time as a tool, not as a couch.", author: "John F. Kennedy"},
    {id:6 ,quote: "Time is a waste of money", author: "Oscar Wilde"},
    {id:7 ,quote: "I am definitely going to take a course on time management … just as soon as I can work it into my schedule.", author: "Louis E. Boone"}
];

const quoteEnglishBeYourself3 = [
    {id:1 ,quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde"},
    {id:2 ,quote: "The most important consequence of self-sufficiency is freedom.", author: "Epicurus"},
    {id:3 ,quote: "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.", author: "Bindi Irwin"},
    {id:4 ,quote: "Can you remember who you were, before the world told you who you should be?", author: "Charles Bukowski"},
    {id:5 ,quote: "If you don't set your own values, other people will.", author: "Shane Parrish"},
    {id:6 ,quote: "You change the world by being yourself.", author: "Yoko Ono"},
    {id:7 ,quote: "Trying to define yourself is like trying to bite your own teeth.", author: "Alan Watts"},
    {id:8 ,quote: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung"},
    {id:9 ,quote: "You are who you are when nobody's watching.", author: "Stephen Fry"},
    {id:10 ,quote: "Existence wants you to be you.", author: "Osho"},
    {id:11 ,quote: "No one ever made a difference by being like everyone else.", author: "Buckminster Fuller"},
    {id:12 ,quote: "When someone is properly grounded in life, they shouldn't have to look outside themselves for approval.", author: "Epictetus"},
    {id:13 ,quote: "You eliminate competition by being yourself.", author: "Dan Go"},
    {id:14 ,quote: "The tighter you cling to your current identity, the harder it becomes to grow beyond it.", author: "James Clear"}
];

const quoteEnglishStrength4 = [
    {id:1 ,quote: "Do not judge me by my success, judge me by how many times I fell down and got back up again.", author: "Nelson Mandela"},
    {id:2 ,quote: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King, Jr."},
    {id:3 ,quote: "We will either find a way, or make one.", author: "Anibal Barca."},
    {id:4 ,quote: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou"},
    {id:5 ,quote: "When you have exhausted all possibilities, remember this: you haven't.", author: "Thomas A. Edison"},
    {id:6 ,quote: "We do not have to become heroes overnight. Just a step at a time, meeting each thing that comes up, seeing it is not as dreadful as it appeared, discovering we have the strength to stare it down.", author: "Eleanor Roosevelt"},
    {id:7 ,quote: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"},
    {id:8 ,quote: "Mastering others is strength, mastering yourself is true power.", author: "Lao Tzu"},
    {id:9 ,quote: "Life is very interesting…in the end, some of your greatest pains become your greatest strengths.", author: "Drew Barrymore."},
    {id:10 ,quote: "Where there is no struggle, there is no strength.", author: "Oprah Winfrey"},
    {id:11 ,quote: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.", author: "Hellen Keller"},
    {id:12 ,quotew: "The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.", author: "Criss Jami"}
];

const quoteEnglishPositive5 = [
    {id:1 ,quote: "There is a force in the universe, which, if we permit it, will flow through us and produce miraculous results.", author: "Mahatma Gandhi"},
    {id:2 ,quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey"},
    {id:3 ,quote: "I am in the right place, at the right time, doing the right thing.", author: "Louise Hay"},
    {id:4 ,quote: "As soon as you trust yourself, you will know how to live.", author: "John Wolfgang von Goethe"},
    {id:5 ,quote: "If the future road looks ominous or unpromising, and the roads back uninviting, then we need to gather our resolve and carrying only the necessary baggage, step off that road and into another direction. ", author: "Maya Angelou"},
    {id:6 ,quote: "What matters most is how you walk through the fire.", author: "Charles Bukowski"},
    {id:7 ,quote: "Reality is something you rise above.", author: "Liza Minnelli"},
    {id:8 ,quote: "Imagination is everything. It is the preview of life's coming attractions.", author: "Albert Einstein"},
    {id:9 ,quote: "There will come a time when you believe everything is finished. That will be the beginning.", author: "Louis L'Amour"},
    {id:10 ,quote: "In the depth of winter, I finally learned that within me lies an invincible summer.", author: "Albert Camus"},
    {id:11 ,quote: "In this world the unseen has power.", author: "Apache proverb"},
    {id:12 ,quote: "Remember that you are unique. If that is not fulfilled, then something wonderful has been lost.", author: "Martha Graham"},
    {id:13 ,quote: "Hello, fear. Thank you for being here. You're my indication that I'm doing what I need to do", author: "Cheryl Strayed in Brave Enough"},
    {id:14 ,quote: "As we each step into our divine life purpose, we really are changing the world. The world needs us now.", author: "Justin Michael Williams"},
    {id:15 ,quote: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi"},
    {id:16 ,quote: "I was made exactly the way I was meant to be made in who I am and my personality and the way I was born.", author: "Megan Rapinoe"},
    {id:17 ,quote: "We're all given something to do. And when we don't follow what we're supposed to do, we always know when we're off track.", author: "Joy Harjo"},
    {id:18 ,quote: "Magical things happen because we exist as part of the great mystery. We don't need an answer to everything that happens to us.", author: "Grandmother Flordemayo"},
    {id:19 ,quote: "The key is to be here fully connected with the moment, paying attention to the ordinary details of life.", author: "Pema Chödrön"},
    {id:20 ,quote: "I have met myself and I am going to care for her fiercely.", author: "Glennon Doyle"},
    {id:21 ,quote: "Nothing is impossible. The word itself says `I'm possible`.", author: "Audrey Hepburn"},
    {id:22 ,quote: "It's kind of fun to do the impossible.", author: "Walt Disney"}
];

const quoteEnglishConfidence6 = [
    {id:1 ,quote: "Until you value yourself, you won't value your time. Until you value your time, you will not do anything with it. ", author: "M. Scott Peck, psychiatrist"},
    {id:2 ,quote: "Because one is content with oneself, one doesn't need others approval", author: "Laozi, ancient philosopher"},
    {id:3 ,quote: "“When you have a lot of confidence and you feel like nobody can beat you, it's game over for everyone else.", author: "Jason Day, pro golfer"},
    {id:4 ,quote: "Self-confidence can be learned, practiced, and mastered—just like any other skill. Once you master it, everything in your life will change for the better.", author: "Barrie Davenport, self-improvement guru"},
    {id:5 ,quote: "It took me a long time not to judge myself through someone else's eyes.", author: "Sally Field, actress and director"},
    {id:6 ,quote: "Confidence doesn't come out of nowhere. It's a result of…hours and days and weeks and years of constant work and dedication.", author: "Roger Staubach, pro football player"},
    {id:7 ,quote: "With confidence, you have won before you have started.", author: "Marcus Garvey, activist and orator"},
    {id:8 ,quote: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde, writer"},
    {id:9 ,quote: "Experience tells you what to do; confidence allows you to do it.", author: "Stan Smith, tennis player"},
    {id:10 ,quote: "Skill and confidence are an unconquered army.", author: "George Herbert, poet"},
    {id:11 ,quote: "When you have confidence, you can have a lot of fun. And when you have fun, you can do amazing things.", author: "Joe Namath, football player"},
    {id:12 ,quote: "“Get more confidence by doing things that excite and frighten you.", author: "Jessica Williams, actress"},
    {id:13 ,quote: "Nurture your mind with great thoughts, for you will never go any higher than you think.", author: "Benjamin Disraeli, former UK Prime Minister"},
    {id:14 ,quote: "Once you become self-conscious, there is no end to it; once you start to doubt, there is no room for anything else.", author: "Mignon McLaughlin"},
    {id:15 ,quote: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Laozi."}
];

const quoteEnglishKindness7 = [
    {id:1 ,quote: "Carry out a random act of kindness, with no expectation of reward, safe in the knowledge that one day someone might do the same for you.", author: "Princess Diana."},
    {id:2 ,quote: "Remember, there's no such thing as a small act of kindness. Every act creates a ripple with no logical end.", author: "Scott Adams"},
    {id:3 ,quote: "Human kindness has never weakened the stamina or softened the fiber of a free people.", author: "Franklin D. Roosevelt."},
    {id:4 ,quote: "When you callously ignore the suffering of others, you lose the capacity to share their happiness, too.", author: "Albert Schweitzer."},
    {id:5 ,quote: "A kind word is like a spring day.", author: "Russian proverb"},
    {id:6 ,quote: "Do things for people not because of who they are or what they do in return, but because of who you are.", author: "Harold S. Kushner"},
    {id:7 ,quote: "You can accomplish by kindness what you cannot by force.", author: "Publilius Syrus"},
    {id:8 ,quote: "Kindness is a passport that opens doors and fashions friends. It softens hearts and molds relationships that can last lifetimes.", author: "Joseph B. Wirthlin"},
    {id:9 ,quote: "When I was young, I admired clever people. Now that I am old, I admire kind people.", author: "Abraham Joshua Heschel"},
    {id:10 ,quote: "Never look down on anybody unless you're helping them up.", author: "Jesse Jackson"},
    {id:11 ,quote: "The smallest act of kindness is worth more than the greatest intention.", author: "Kahlil Gibran"},
    {id:12 ,quote: "Kindness is more important than wisdom, and the recognition of this is the beginning of wisdom.", author: "Theodore Isaac Rubin"}
];


//Acá estoy encontrando oro puro
const quoteEnglishSpiritual8 = [
    {id:1 ,quote: "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one which has been opened for us.", author: "Helen Keller"},
    {id:2 ,quote: "Practice the pause. When in doubt, pause. When angry, pause. When tired, pause. When stressed, pause. And when you pause, pray.", author: "Toby Mac"},
    {id:3 ,quote: "If you live up to your privilege, the angels cannot be restrained from being your associates.", author: "Joseph Smith"},
    {id:4 ,quote: "Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.", author: "Wayne Dyer"},
    {id:5 ,quote: "When you consider things like the stars, our affairs don't seem to matter very much, do they?", author: "Virginia Woolf"},
    {id:6 ,quote: "Set peace of mind as your highest goal, and organize your life around it.", author: "Brian Tracy"},
    {id:7 ,quote: "I don't want to cover up anymore. Not my face, not my mind, not my soul, not my thoughts, not my dreams, not my struggles, not my emotional growth. Nothing.", author: "Alicia Keys"},
    {id:8 ,quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"},
    {id:9 ,quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi"},
    {id:10 ,quote: "To have been loved so deeply, even though the person who loved us is gone, will give us some protection forever.", author: "J.K. Rowling, Harry Potter"},
    {id:11 ,quote: "“If you don't like the road you're walking, start paving another one.", author: "Dolly Parton"},
    {id:12 ,quote: "God whispers to us in our pleasures, speaks in our consciences, but shouts in our pains. It is his megaphone to rouse a deaf world.", author: "C.S. Lewis, The Problem of Pain"},
    {id:13 ,quote: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien, The Fellowship of the Ring"},
    {id:14 ,quote: "Make your own Bible. Select and collect all the words and sentences that in all your readings have been to you like the blast of a trumpet", author: "Ralph Waldo Emerson"},
    {id:15 ,quote: "People seem not to see that their opinion of the world is also a confession of character.", author: "Ralph Waldo Emerson, “Worship”"},
    {id:16 ,quote: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung"},
    {id:17 ,quote: "One must still have chaos in oneself to be able to give birth to a dancing star.", author: "Friedrich Nietzsche"},
    {id:18 ,quote: "I would believe only in a god who could dance. And when I saw my devil I found him serious, thorough, profound, and solemn: it was the spirit of gravity - through him all things fall.", author: "Friedrich Nietzsche"},
    {id:19 ,quote: "And above all, remember that the meaning of life is to build a life as if it were a work of art.", author: "Rabbi Abraham Joshua Heschel"},
    {id:20 ,quote: "Life's barely long enough to get good at one thing. So be careful what you get good at.", author: "Matthew McConaughey as Rust Cohle in True Detective"},
    {id:21 ,quote: "If the sun comes up, I have a chance.", author: "Venus Williams"},
];

const quoteEnglishChange9 = [
    {id:1 ,quote: "The first step toward change is awareness. The second step is acceptance.", author: "Nathaniel Branden"},
    {id:2 ,quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi."},
    {id:3 ,quote: "Life is about not knowing, having to change, taking the moment and making the best of it, without knowing what's going to happen next.", author: "Gilda Radner."},
    {id:4 ,quote: "You never change your life until you step out of your comfort zone; change begins at the end of your comfort zone.", author: "Roy T. Bennett."},
    {id:5 ,quote: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou."},
    {id:6 ,quote: "There is nothing so stable as change.", author: "Bob Dylan"},
    {id:7 ,quote: "We all have big changes in our lives that are more or less a second chance.", author: "Harrison Ford"},
    {id:8 ,quote: "When you come out of the storm, you won't be the same person who walked in. That's what this storm's all about.", author: "Haruki Murakami"},
    {id:9 ,quote: "Things don't have to change the world to be important.", author: "Steve Jobs"},
    {id:10 ,quote: "Let him who would move the world first move himself.", author: "Socrates"},
    {id:11 ,quote: "True life is lived when tiny changes occur.", author: "Leo Tolstoy"},
    {id:12 ,quote: "A bend in the road is not the end of the road…unless you fail to make the turn.", author: "Helen Keller"},
    {id:13 ,quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale"},
    {id:14 ,quote: "Change is hardest at the beginning, messiest in the middle and best at the end.", author: "Robin Sharma"},
    {id:15 ,quote: "Remember that life's big changes rarely give advance warning.", author: "H. Jackson Brown, Jr."},
    {id:16 ,quote: "A tiny change today brings a dramatically different tomorrow.", author: "Richard Bach"},
    {id:17 ,quote: "Anyone who isn't embarrassed of who they were last year probably isn't learning enough.", author: "Alain de Botton"},
    {id:18 ,quote: "Change your life today. Don't gamble on the future, act now, without delay.", author: "Simone de Beauvoir"},
    {id:19 ,quote: "A change is as good as a rest.", author: "Stephen King"},
    {id:20 ,quote: "There are three constants in life…change, choice and principles.", author: "Stephen Covey"},
    {id:21 ,quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean"},
    {id:22 ,quote: "We cannot change the cards we are dealt, just how we play the game.", author: "Randy Pausch"},
    {id:23 ,quote: "The key to change…is to let go of fear.", author: "Rosanne Cash"},
    {id:24 ,quote: "Change is not an event, it's a process.", author: "Cheryl James "},
    {id:24 ,quote: "Every day the clock resets. Your wins don't matter. Your failures don't matter. Don't stress on what was, fight for what could be.", author: "Sean Higgins"}
];

const quoteEnglishSuccess10 = [
    {id:1 ,quote: "I can live with a mistake. What I couldn't live with is sloppiness. And there's a difference.", author: "Dana Canedy"},
    {id:2 ,quote: "I didn't want to be something cool. I didn't want to be calm. I wanted to be a player that made you say, 'Did you see that?'", author: "Kevin Garnett"},
    {id:3 ,quote: "There's a saying that if you do what you love, you'll never work a day in your life. I learned that's a total crock. You'll work harder than you ever thought possible, but the tools will feel light in your hands.", author: "Tim Cook"},
    {id:4 ,quote: "Invest in the success of others. It's not about being the only one that succeeds; it's about multiplying to many.", author: "Steph Curry"},
    {id:5 ,quote: "Spend 30 minutes a day doing something to help you become the person you secretly would love to be. To do the job you secretly would love to do. If I can tell you anything, it's that you can actually do it. It's more than just that what you want to do is possible, because there are people who are doing it and it was impossible for them at one time too.", author: "Tomi Adeyemi"},
    {id:6 ,quote: "Some people feel confusion and uncertainty, (which are often things that arrive right before possibility) and do nothing. Don't do nothing.", author: "Alex Dimitrov"},
    {id:7 ,quote: "There are no miracles. There is only discipline.", author: "Danielle Steel"},
    {id:8 ,quote: "The 'success' parts of life look good to others, but the best parts are actually the simple, daily experiences. This is true whether you're an actor or a teacher or a waitress. I know because I've been all three.", author: "Lauren Graham"},
    {id:9 ,quote: "I haven't made one mistake that I haven't used as a stepping stone to get somewhere else. I'm ruthless when it comes to using hard things.", author: "Gwyneth Paltrow"},
    {id:10 ,quote: "Rules, like streets, can only take you to known places.", author: "Ocean Vuong"},
    {id:11 ,quote: "Start unknown, finish unforgettable.", author: "Misty Copeland"},
    {id:12 ,quote: "Be the hardest working person you know. If you're not, someone else will be.", author: "Ian Brennan"},
    {id:13 ,quote: "I could give example after example of how doing the right thing ended up making us more money.", author: "Yvon Chouinard"},
    {id:14 ,quote: "Age is not the enemy. Stagnation is the enemy. Complacency is the enemy. Stasis is the enemy.", author: "Twyla Tharp"},
    {id:15 ,quote: "The sky isn't the limit—the sky has no limit.", author: "Sarah Barker"},
    {id:16 ,quote: "Work eight hours and sleep eight hours. Make sure they are not the same eight hours.", author: "T. Boone Pickens"},
    {id:17 ,quote: "Don't just stand there; make something happen.", author: "Lee Iacocca"},
    {id:18 ,quote: "Every success is usually an admission ticket to a new set of decisions.", author: "Henry Kissinger"},
    {id:19 ,quote: "Success is a lot like a bright white tuxedo. You feel terrific when you get it, but then you're desperately afraid of getting it dirty, of spoiling it in any way.", author: "Conan O'Brien"},
    {id:20 ,quote: "You only have to do a very few things right in your life—so long as you don't do too many things wrong.", author: "Warren Buffet"},
    {id:21 ,quote: "Anybody who's really successful has doubts.", author: "Jerry Bruckheimer"},
    {id:22 ,quote: "There's a ball. There's a hoop. You put the ball through the hoop. That's success.", author: "Kareem Abdul-Jabbar"},
    {id:23 ,quote: "Success is falling nine times and getting up ten.", author: "Jon Bon Jovi"},
    {id:24 ,quote: "Success is more permanent when you achieve it without destroying your principles.", author: "Walter Cronkite"},
    {id:25 ,quote: "If you want to be successful, just meditate, man. God will tell you what people need.", author: "Carlos Santana"},
    {id:26 ,quote: "There is no point at which you can say, 'Well, I'm successful now. I might as well take a nap.", author: "Carrie Fisher"},
    {id:27 ,quote: "Winning depends on where you put your priorities. It's usually best to put them over the fence.", author: "Jason Giambi"},
    {id:28 ,quote: "Celebrate what you've accomplished, but raise the bar a little higher each time you succeed.", author: "Mia Hamm"},
    {id:29 ,quote: "You cannot be really first-rate at your work if your work is all you are.", author: "Anna Quindlen"},
    {id:30 ,quote: "Inside of a ring or out, ain't nothing wrong with going down. It's staying down that's wrong.", author: "Muhammad Ali"},
    {id:31 ,quote: "The person who knows 'how' will always have a job. The person who knows 'why' will always be his boss.", author: "Diane Ravitch"}
];

const quoteEnglishDreamBig11 = [
    {id:1 ,quote: "So many of our dreams at first seem impossible, then they seem improbable, and then, when we summon the will, they soon become inevitable.", author: "Christopher Reeve"},
    {id:2 ,quote: "A great leader's courage to fulfill his vision comes from passion, not position.", author: "John Maxwell"},
    {id:3 ,quote: "Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman"},
    {id:4 ,quote: "Whatever you do, or dream you can, begin it. Boldness has genius and power and magic in it.", author: "Goethe"},
    {id:5 ,quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"},
    {id:6 ,quote: "Each man should frame life so that at some future hour fact and his dreaming meet.", author: "Victor Hugo"},
    {id:7 ,quote: "All successful people men and women are big dreamers. They imagine what their future could be, ideal in every respect, and then they work every day toward their distant vision, that goal or purpose.", author: "Brian Tracy"},
    {id:8 ,quote: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney"},
    {id:9 ,quote: "For once you have tasted flight you will walk the earth with your eyes turned skywards, for there you have been and there you will long to return.", author: "Leonardo da Vinci"},
    {id:11 ,quote: "Dreams are the touchstones of our character.", author: "Henry David Thoreau"},
    {id:12 ,quote: "Dreams come in a size too big so that we may grow into them.", author: "Josie Bisse"},
    {id:13 ,quote: "Ask yourself, 'How long am I going to work to make my dreams come true?' I suggest you answer, As long as it takes.'", author: "Jim Rohn"},
    {id:14 ,quote: "Dreams are renewable. No matter what our age or condition, there are still untapped possibilities within us and new beauty waiting to be born.", author: "Dr. Dale E. Turner"},
    {id:15 ,quote: "Be willing to be uncomfortable. Be comfortable being uncomfortable. It may get tough, but it's a small price to pay for living a dream", author: "Peter McWilliams."},
    {id:16 ,quote: "Dream and give yourself permission to envision a you that you choose to be.", author: "Joy Page."},
    {id:17 ,quote: "If you don't build your dream, someone will hire you to help build theirs.", author: "Tony Gaskins"},
    {id:18 ,quote: "You are never too old to set another goal or to dream a new dream.", author: "C. S. Lewis"},
    {id:19 ,quote: "If you take responsibility for yourself you will develop a hunger to accomplish your dreams.", author: "Les Brown."},
    {id:20 ,quote: "Don't be afraid of the space between your dreams and reality. If you can dream it, you can make it so.", author: "Belva Davis."}
];

const quoteEnglish12 = [
    {id:1 ,quote: "", author: ""},
    {id:2 ,quote: "", author: ""},
    {id:3 ,quote: "", author: ""},
    {id:4 ,quote: "", author: ""},
    {id:5 ,quote: "", author: ""},
    {id:6 ,quote: "", author: ""},
    {id:7 ,quote: "", author: ""},
    {id:8 ,quote: "", author: ""},
    {id:9 ,quote: "", author: ""},
    {id:10 ,quote: "", author: ""},
    {id:11 ,quote: "", author: ""},
    {id:12 ,quote: "", author: ""},
    {id:13 ,quote: "", author: ""},
    {id:14 ,quote: "", author: ""},
    {id:15 ,quote: "", author: ""},
    {id:16 ,quote: "", author: ""},
    {id:17 ,quote: "", author: ""}
];